<?php

use Illuminate\Database\Seeder;

class LookupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lookups')->delete();
        
        \DB::table('lookups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'person_title',
                'value' => 'Mr',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Person Tile',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 12:08:49',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'person_title',
                'value' => 'Mrs',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Person Title',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 10:19:55',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'person_title',
                'value' => 'Ms',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Person Title',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 10:19:59',
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'person_title',
                'value' => 'Dr',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Person Title',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 10:20:08',
            ),
            4 => 
            array (
                'id' => 12,
                'code' => 'temp_section',
                'value' => 'Template Section',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Template Section',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:13:35',
                'updated_at' => '2018-04-02 08:18:39',
            ),
            5 => 
            array (
                'id' => 13,
                'code' => 'temp_section',
                'value' => 'Department',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Department',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:13:50',
                'updated_at' => '2018-04-02 08:18:46',
            ),
            6 => 
            array (
                'id' => 14,
                'code' => 'temp_type',
                'value' => 'Report',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Report',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:19:01',
                'updated_at' => '2018-04-02 08:19:27',
            ),
            7 => 
            array (
                'id' => 15,
                'code' => 'temp_type',
                'value' => 'Email',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Email',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:19:11',
                'updated_at' => '2018-04-02 08:19:37',
            ),
            8 => 
            array (
                'id' => 16,
                'code' => 'temp_type',
                'value' => 'Mail',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Mail',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:19:55',
                'updated_at' => '2018-04-02 08:19:55',
            ),
            9 => 
            array (
                'id' => 17,
                'code' => 'temp_type',
                'value' => 'Terms',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Terms',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 08:20:14',
                'updated_at' => '2018-04-02 08:20:14',
            ),
            10 => 
            array (
                'id' => 18,
                'code' => 'note_priority',
                'value' => 'High',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 11:12:16',
                'updated_at' => '2018-06-22 10:17:28',
            ),
            11 => 
            array (
                'id' => 19,
                'code' => 'note_priority',
                'value' => 'Standard',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Standard',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 11:12:27',
                'updated_at' => '2018-06-22 10:17:35',
            ),
            12 => 
            array (
                'id' => 21,
                'code' => 'note_status',
                'value' => 'Done',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Done Status',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 11:12:57',
                'updated_at' => '2018-06-22 10:17:43',
            ),
            13 => 
            array (
                'id' => 22,
                'code' => 'note_type',
                'value' => 'Todo',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Todo type',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 11:13:17',
                'updated_at' => '2018-06-22 10:18:08',
            ),
            14 => 
            array (
                'id' => 23,
                'code' => 'note_activity',
                'value' => 'Application',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Application Activity',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 11:13:26',
                'updated_at' => '2018-06-22 10:17:11',
            ),
            15 => 
            array (
                'id' => 24,
                'code' => 'mail_sp',
                'value' => 'Fedex',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 13:06:06',
                'updated_at' => '2018-06-22 10:21:53',
            ),
            16 => 
            array (
                'id' => 25,
                'code' => 'mail_sp',
                'value' => 'DHL',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 13:06:13',
                'updated_at' => '2018-06-22 10:21:58',
            ),
            17 => 
            array (
                'id' => 26,
                'code' => 'letter_status',
                'value' => 'Pending',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 13:22:30',
                'updated_at' => '2019-04-05 08:31:50',
            ),
            18 => 
            array (
                'id' => 27,
                'code' => 'letter_status',
                'value' => 'Shipped',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 13:22:37',
                'updated_at' => '2018-06-22 10:21:26',
            ),
            19 => 
            array (
                'id' => 28,
                'code' => 'letter_status',
                'value' => 'Cancelled',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => NULL,
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-02 13:22:43',
                'updated_at' => '2018-06-22 10:21:31',
            ),
            20 => 
            array (
                'id' => 37,
                'code' => 'note_status',
                'value' => 'Not Done',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Not Done Status',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 04:17:18',
                'updated_at' => '2018-06-22 10:17:47',
            ),
            21 => 
            array (
                'id' => 38,
                'code' => 'note_status',
                'value' => 'Approved',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Approved Status',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 04:17:33',
                'updated_at' => '2018-06-22 10:17:53',
            ),
            22 => 
            array (
                'id' => 39,
                'code' => 'note_status',
                'value' => 'Completed',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Completed Status',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 04:17:47',
                'updated_at' => '2018-06-22 10:17:58',
            ),
            23 => 
            array (
                'id' => 40,
                'code' => 'note_type',
                'value' => 'Task',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Task',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 04:19:02',
                'updated_at' => '2018-06-22 10:18:13',
            ),
            24 => 
            array (
                'id' => 41,
                'code' => 'note_type',
                'value' => 'Reminder',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Reminder',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 04:19:14',
                'updated_at' => '2018-06-22 10:18:17',
            ),
            25 => 
            array (
                'id' => 57,
                'code' => 'sex',
                'value' => 'Male',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Male',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-13 13:43:22',
                'updated_at' => '2018-06-22 10:23:08',
            ),
            26 => 
            array (
                'id' => 58,
                'code' => 'sex',
                'value' => 'Female',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Female',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-13 13:43:31',
                'updated_at' => '2018-06-22 10:23:14',
            ),
            27 => 
            array (
                'id' => 59,
                'code' => 'sex',
                'value' => 'Others',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Others',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-13 13:43:50',
                'updated_at' => '2018-06-22 10:23:21',
            ),
            28 => 
            array (
                'id' => 77,
                'code' => 'report_format',
                'value' => 'csv',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Report formate
supported csv,json,pdf,excel',
                'section' => 'Report',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-15 02:36:28',
                'updated_at' => '2018-06-22 12:15:52',
            ),
            29 => 
            array (
                'id' => 78,
                'code' => 'report_format',
                'value' => 'json',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Report format
supported csv,json,pdf,excel',
                'section' => 'Report',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-15 02:36:45',
                'updated_at' => '2018-06-22 12:16:05',
            ),
            30 => 
            array (
                'id' => 79,
                'code' => 'report_format',
                'value' => 'pdf',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Report formate
supported csv,json,pdf,excel',
                'section' => 'Report',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-15 02:36:59',
                'updated_at' => '2018-06-22 12:16:32',
            ),
            31 => 
            array (
                'id' => 80,
                'code' => 'report_format',
                'value' => 'excel',
                'type' => NULL,
                'sequence_num' => 4,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Report formate
supported csv,json,pdf,excel',
                'section' => 'Report',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-15 02:37:44',
                'updated_at' => '2018-06-22 12:16:48',
            ),
            32 => 
            array (
                'id' => 85,
                'code' => 'phone_type',
                'value' => 'Home',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Phone type',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 11:10:00',
                'updated_at' => '2018-06-22 10:20:31',
            ),
            33 => 
            array (
                'id' => 86,
                'code' => 'phone_type',
                'value' => 'Office',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Phone Type',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 11:10:18',
                'updated_at' => '2018-06-22 10:20:36',
            ),
            34 => 
            array (
                'id' => 88,
                'code' => 'support_type',
                'value' => 'Bug',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'bug support',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:38:40',
                'updated_at' => '2018-06-08 06:38:40',
            ),
            35 => 
            array (
                'id' => 89,
                'code' => 'support_type',
                'value' => 'Error',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Error type',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:38:58',
                'updated_at' => '2018-06-08 06:38:58',
            ),
            36 => 
            array (
                'id' => 90,
                'code' => 'support_type',
                'value' => 'Training',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Training',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:39:18',
                'updated_at' => '2018-06-08 06:39:18',
            ),
            37 => 
            array (
                'id' => 91,
                'code' => 'support_type',
                'value' => 'Installation',
                'type' => NULL,
                'sequence_num' => 4,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Installation',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:39:44',
                'updated_at' => '2018-06-08 06:39:44',
            ),
            38 => 
            array (
                'id' => 92,
                'code' => 'support_type',
                'value' => 'Forum',
                'type' => NULL,
                'sequence_num' => 5,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Forum question and anwers',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:40:08',
                'updated_at' => '2018-06-08 06:40:08',
            ),
            39 => 
            array (
                'id' => 93,
                'code' => 'support_category',
                'value' => 'support',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Support',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:40:53',
                'updated_at' => '2018-06-08 06:40:53',
            ),
            40 => 
            array (
                'id' => 94,
                'code' => 'support_category',
                'value' => 'developer',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Developer',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:41:07',
                'updated_at' => '2018-06-08 06:41:07',
            ),
            41 => 
            array (
                'id' => 95,
                'code' => 'support_category',
                'value' => 'version',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'version',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:41:25',
                'updated_at' => '2018-06-08 06:41:25',
            ),
            42 => 
            array (
                'id' => 96,
                'code' => 'support_category',
                'value' => 'forum',
                'type' => NULL,
                'sequence_num' => 4,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'forum',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:41:47',
                'updated_at' => '2018-06-08 06:41:47',
            ),
            43 => 
            array (
                'id' => 97,
                'code' => 'support_department',
                'value' => 'sales',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'sales',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:42:03',
                'updated_at' => '2018-06-08 06:42:03',
            ),
            44 => 
            array (
                'id' => 98,
                'code' => 'support_department',
                'value' => 'development',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Development',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:42:34',
                'updated_at' => '2018-06-08 06:42:34',
            ),
            45 => 
            array (
                'id' => 99,
                'code' => 'support_department',
                'value' => 'billing',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Billing',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:42:45',
                'updated_at' => '2018-06-08 06:42:45',
            ),
            46 => 
            array (
                'id' => 100,
                'code' => 'support_department',
                'value' => 'CSD',
                'type' => NULL,
                'sequence_num' => 4,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Customer Support Department',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 06:43:25',
                'updated_at' => '2018-06-08 06:43:25',
            ),
            47 => 
            array (
                'id' => 101,
                'code' => 'note_activity',
                'value' => 'Invoice',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Invoice Activity',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 2,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-14 11:53:07',
                'updated_at' => '2018-06-22 10:17:16',
            ),
            48 => 
            array (
                'id' => 102,
                'code' => 'note_activity',
                'value' => 'Payment',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Payment Related Activity',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 2,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-14 11:53:39',
                'updated_at' => '2018-06-22 10:17:21',
            ),
            49 => 
            array (
                'id' => 112,
                'code' => 'phone_type',
                'value' => 'Cell',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Cell',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-07-04 07:23:14',
                'updated_at' => '2018-07-04 07:23:14',
            ),
            50 => 
            array (
                'id' => 113,
                'code' => 'phone_type',
                'value' => 'Emergency Contact',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Emergency Contact',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-07-04 07:29:08',
                'updated_at' => '2018-07-04 07:29:08',
            ),
            51 => 
            array (
                'id' => 118,
                'code' => 'volunteer_details',
                'value' => 'Base pay rate',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'integer',
                'has_lookup' => 0,
                'description' => 'base pay rate',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-14 11:36:42',
                'updated_at' => '2019-04-23 08:19:50',
            ),
            52 => 
            array (
                'id' => 119,
                'code' => 'volunteer_details',
                'value' => 'Stipend eligibility',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => 'check whether the have the stipend eligibility or not',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-14 11:40:06',
                'updated_at' => '2019-03-14 11:40:06',
            ),
            53 => 
            array (
                'id' => 120,
                'code' => 'stipend_eligibility',
                'value' => 'yes',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'if he has stipend',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 07:18:10',
                'updated_at' => '2019-03-15 07:18:10',
            ),
            54 => 
            array (
                'id' => 121,
                'code' => 'volunteer_details',
                'value' => 'Date of birth',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'date',
                'has_lookup' => 0,
                'description' => 'date of birth',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 07:31:10',
                'updated_at' => '2019-04-23 08:19:55',
            ),
            55 => 
            array (
                'id' => 122,
                'code' => 'template_option',
                'value' => 'Mileage Reimbursements',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:15:19',
                'updated_at' => '2019-03-15 15:15:19',
            ),
            56 => 
            array (
                'id' => 123,
                'code' => 'template_option',
                'value' => 'Food Service',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:15:58',
                'updated_at' => '2019-03-15 15:15:58',
            ),
            57 => 
            array (
                'id' => 124,
                'code' => 'travel_option',
                'value' => 'Bus',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:16:45',
                'updated_at' => '2019-03-15 15:16:45',
            ),
            58 => 
            array (
                'id' => 125,
                'code' => 'travel_option',
                'value' => 'Drive',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:16:58',
                'updated_at' => '2019-03-15 15:16:58',
            ),
            59 => 
            array (
                'id' => 126,
                'code' => 'travel_option',
                'value' => 'Para',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:17:08',
                'updated_at' => '2019-03-15 15:17:08',
            ),
            60 => 
            array (
                'id' => 127,
                'code' => 'travel_option',
                'value' => 'Walk',
                'type' => NULL,
                'sequence_num' => 4,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:17:21',
                'updated_at' => '2019-03-15 15:17:21',
            ),
            61 => 
            array (
                'id' => 128,
                'code' => 'travel_option',
                'value' => 'Carpool',
                'type' => NULL,
                'sequence_num' => 5,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:17:30',
                'updated_at' => '2019-03-15 15:17:30',
            ),
            62 => 
            array (
                'id' => 129,
                'code' => 'meal_option',
                'value' => 'Yes',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:17:54',
                'updated_at' => '2019-03-15 15:17:54',
            ),
            63 => 
            array (
                'id' => 130,
                'code' => 'meal_option',
                'value' => 'No',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:18:03',
                'updated_at' => '2019-03-15 15:18:03',
            ),
            64 => 
            array (
                'id' => 131,
                'code' => 'meal_option',
                'value' => 'Bag',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => NULL,
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-15 15:18:12',
                'updated_at' => '2019-03-15 15:18:12',
            ),
            65 => 
            array (
                'id' => 134,
                'code' => 'CodeCategory',
                'value' => 'Mileage Reimbursements',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Travel Category',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 13:50:33',
                'updated_at' => '2019-04-02 06:38:00',
            ),
            66 => 
            array (
                'id' => 135,
                'code' => 'CodeCategory',
                'value' => 'Food Service',
                'type' => NULL,
                'sequence_num' => 3,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Meal Category',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:43:52',
                'updated_at' => '2019-04-02 06:38:16',
            ),
            67 => 
            array (
                'id' => 136,
                'code' => 'CodeCategory',
                'value' => 'Type',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Type Category',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:44:13',
                'updated_at' => '2019-04-02 06:38:32',
            ),
            68 => 
            array (
                'id' => 137,
                'code' => 'Account',
                'value' => '55100',
                'type' => 'Type',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Stipends',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:44:52',
                'updated_at' => '2019-03-28 06:44:52',
            ),
            69 => 
            array (
                'id' => 138,
                'code' => 'Account',
                'value' => '55641',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Mileage',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:45:12',
                'updated_at' => '2019-03-28 06:45:12',
            ),
            70 => 
            array (
                'id' => 139,
                'code' => 'Account',
                'value' => '55658',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Meals',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:45:34',
                'updated_at' => '2019-03-28 06:45:34',
            ),
            71 => 
            array (
                'id' => 140,
                'code' => 'phone_type',
                'value' => 'Other',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 1,
                'description' => 'Other',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 15:27:49',
                'updated_at' => '2019-03-28 15:27:49',
            ),
            72 => 
            array (
                'id' => 141,
                'code' => 'Project',
                'value' => '11646',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Mileage Project',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:46:39',
                'updated_at' => '2019-04-02 09:24:49',
            ),
            73 => 
            array (
                'id' => 142,
                'code' => 'Business',
                'value' => '35000',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Business Unit',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:49:38',
                'updated_at' => '2019-03-28 06:49:38',
            ),
            74 => 
            array (
                'id' => 143,
                'code' => 'Department',
                'value' => '351230',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Department Code',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:50:07',
                'updated_at' => '2019-03-28 06:50:07',
            ),
            75 => 
            array (
                'id' => 144,
                'code' => 'Fund',
                'value' => '100',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Stipend Fund code',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:50:31',
                'updated_at' => '2019-03-28 06:50:31',
            ),
            76 => 
            array (
                'id' => 145,
                'code' => 'Fund',
                'value' => '225',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Meals/Mileage Fund Code',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:50:56',
                'updated_at' => '2019-03-28 06:50:56',
            ),
            77 => 
            array (
                'id' => 146,
                'code' => 'Program',
                'value' => '3DC64',
                'type' => 'Mileage Reimbursements',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Program Code',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-28 06:51:22',
                'updated_at' => '2019-03-28 06:51:22',
            ),
            78 => 
            array (
                'id' => 147,
                'code' => 'Program',
                'value' => '5afs3',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Program code Second',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 148,
                'code' => 'industry_type',
                'value' => 'Information Technology',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Information Technology',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-29 08:45:33',
                'updated_at' => '2019-03-29 08:45:33',
            ),
            80 => 
            array (
                'id' => 149,
                'code' => 'industry_type',
                'value' => 'Service',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Service',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-29 08:46:25',
                'updated_at' => '2019-03-29 08:46:25',
            ),
            81 => 
            array (
                'id' => 150,
                'code' => 'industry_type',
                'value' => 'Manufacturing',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Manufacturing Company',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-29 08:46:37',
                'updated_at' => '2019-03-29 08:46:37',
            ),
            82 => 
            array (
                'id' => 151,
                'code' => 'industry_type',
                'value' => 'Tourism',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Tourism Industry',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-29 08:47:00',
                'updated_at' => '2019-03-29 08:47:00',
            ),
            83 => 
            array (
                'id' => 152,
                'code' => 'organization_detail',
                'value' => 'Label One',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Test',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:05:43',
                'updated_at' => '2019-04-01 07:06:45',
            ),
            84 => 
            array (
                'id' => 153,
                'code' => 'organization_detail',
                'value' => 'Label Two',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Test 2',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:06:07',
                'updated_at' => '2019-04-01 07:06:50',
            ),
            85 => 
            array (
                'id' => 154,
                'code' => 'organization_detail',
                'value' => 'Labe Three',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Test 3',
                'section' => 'Organization',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:06:26',
                'updated_at' => '2019-04-01 07:06:56',
            ),
            86 => 
            array (
                'id' => 155,
                'code' => 'field_type',
                'value' => 'input',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Input field type.',
                'section' => 'StipendItem',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:58:13',
                'updated_at' => '2019-04-01 07:58:13',
            ),
            87 => 
            array (
                'id' => 156,
                'code' => 'field_type',
                'value' => 'select',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Select option type',
                'section' => 'StipendItem',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:58:39',
                'updated_at' => '2019-04-01 07:58:39',
            ),
            88 => 
            array (
                'id' => 157,
                'code' => 'field_type',
                'value' => 'checkbox',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'checkbox input type',
                'section' => 'StipendItem',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-01 07:58:55',
                'updated_at' => '2019-04-01 07:58:55',
            ),
            89 => 
            array (
                'id' => 158,
                'code' => 'Fund',
                'value' => '00900',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'test',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 07:18:27',
                'updated_at' => '2019-04-02 07:26:42',
            ),
            90 => 
            array (
                'id' => 159,
                'code' => 'site_type',
                'value' => 'School',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Site Type School',
                'section' => 'Site',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 08:53:53',
                'updated_at' => '2019-04-02 08:53:53',
            ),
            91 => 
            array (
                'id' => 160,
                'code' => 'site_type',
                'value' => 'Church',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Site Type Church',
                'section' => 'Site',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 08:54:09',
                'updated_at' => '2019-04-02 08:54:09',
            ),
            92 => 
            array (
                'id' => 161,
                'code' => 'site_type',
                'value' => 'Community',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Site Type Community',
                'section' => 'Site',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 08:54:31',
                'updated_at' => '2019-04-02 08:54:31',
            ),
            93 => 
            array (
                'id' => 162,
                'code' => 'Project',
                'value' => '090909',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Project meal',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 09:25:19',
                'updated_at' => '2019-04-02 09:25:19',
            ),
            94 => 
            array (
                'id' => 163,
                'code' => 'Project',
                'value' => '898989',
                'type' => 'Type',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Test Type',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 09:25:41',
                'updated_at' => '2019-04-02 09:25:41',
            ),
            95 => 
            array (
                'id' => 164,
                'code' => 'Department',
                'value' => '2323',
                'type' => 'Food Service',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Department test meal',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 09:26:10',
                'updated_at' => '2019-04-02 09:26:10',
            ),
            96 => 
            array (
                'id' => 165,
                'code' => 'Department',
                'value' => '2323',
                'type' => 'Type',
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'test',
                'section' => 'FinanceCode',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-02 09:26:21',
                'updated_at' => '2019-04-02 09:26:21',
            ),
            97 => 
            array (
                'id' => 166,
                'code' => 'time_type',
                'value' => 'Regular',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Regular',
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:28',
                'updated_at' => '2019-04-05 08:16:28',
            ),
            98 => 
            array (
                'id' => 167,
                'code' => 'time_type',
                'value' => 'Jury Duty',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Jury Duty',
                'section' => 'Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:46',
                'updated_at' => '2019-04-05 08:16:46',
            ),
            99 => 
            array (
                'id' => 168,
                'code' => 'payment_code',
                'value' => 'Check',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Payment method',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:46',
                'updated_at' => '2019-04-05 08:16:46',
            ),
            100 => 
            array (
                'id' => 169,
                'code' => 'payment_code',
                'value' => 'ACH',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Payment method',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:46',
                'updated_at' => '2019-04-05 08:16:46',
            ),
            101 => 
            array (
                'id' => 170,
                'code' => 'vol_id_type',
                'value' => 'Passport',
                'type' => NULL,
                'sequence_num' => 1,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Payment method',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:46',
                'updated_at' => '2019-04-05 08:16:46',
            ),
            102 => 
            array (
                'id' => 171,
                'code' => 'vol_id_type',
                'value' => 'Driving License',
                'type' => NULL,
                'sequence_num' => 2,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Payment method',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-05 08:16:46',
                'updated_at' => '2019-04-05 08:16:46',
            ),
            103 => 
            array (
                'id' => 172,
                'code' => 'volunteerStatus',
                'value' => 'Applied',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Applied',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:46:46',
                'updated_at' => '2019-07-22 06:46:46',
            ),
            104 => 
            array (
                'id' => 173,
                'code' => 'volunteerStatus',
                'value' => 'Approved',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Approved',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:47:47',
                'updated_at' => '2019-07-22 06:47:47',
            ),
            105 => 
            array (
                'id' => 174,
                'code' => 'volunteerStatus',
                'value' => 'Ineligible',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Ineligible',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:48:46',
                'updated_at' => '2019-07-22 06:48:46',
            ),
            106 => 
            array (
                'id' => 175,
                'code' => 'volunteerStatus',
                'value' => 'Retired',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Retired',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:49:12',
                'updated_at' => '2019-07-22 06:49:12',
            ),
            107 => 
            array (
                'id' => 176,
                'code' => 'volunteerStatus',
                'value' => 'Deceased',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Deceased',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:49:48',
                'updated_at' => '2019-07-22 06:49:48',
            ),
            108 => 
            array (
                'id' => 177,
                'code' => 'volunteerStatus',
                'value' => 'Unpaid',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Unpaid',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:50:21',
                'updated_at' => '2019-07-22 06:50:21',
            ),
            109 => 
            array (
                'id' => 178,
                'code' => 'volunteerStatus',
                'value' => 'Inactive',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Volunteer Status Inactive',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:50:44',
                'updated_at' => '2019-07-22 06:50:44',
            ),
            110 => 
            array (
                'id' => 179,
                'code' => 'volunteerDeactivationReason',
                'value' => 'Retired',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Deactivation Reason Retired',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:52:07',
                'updated_at' => '2019-07-22 06:52:07',
            ),
            111 => 
            array (
                'id' => 180,
                'code' => 'volunteerDeactivationReason',
                'value' => 'Deceased',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Deactivation Reason Deceased',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:52:55',
                'updated_at' => '2019-07-22 06:52:55',
            ),
            112 => 
            array (
                'id' => 181,
                'code' => 'volunteerDeactivationReason',
                'value' => 'Disability',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Deactivation Reason Disability',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:53:36',
                'updated_at' => '2019-07-22 06:53:36',
            ),
            113 => 
            array (
                'id' => 182,
                'code' => 'volunteerDeactivationReason',
                'value' => 'Dismissal',
                'type' => NULL,
                'sequence_num' => NULL,
                'datatype' => 'string',
                'has_lookup' => 0,
                'description' => 'Deactivation Reason Dismissal',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-22 06:53:56',
                'updated_at' => '2019-07-22 06:53:56',
            ),
        ));
        
        
    }
}