<?php

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'page_name' => 'Dashboard',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'page_name' => 'client',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:00:13',
                'updated_at' => '2018-04-03 17:00:13',
            ),
            2 => 
            array (
                'id' => 3,
                'page_name' => 'calendar',
                'action' => 'add|view|delete|edit',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:01:07',
                'updated_at' => '2018-04-03 17:01:07',
            ),
            3 => 
            array (
                'id' => 4,
                'page_name' => 'note',
                'action' => 'view|add|edit|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:01:25',
                'updated_at' => '2018-04-03 17:01:25',
            ),
            4 => 
            array (
                'id' => 5,
                'page_name' => 'Reports',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:04:35',
                'updated_at' => '2018-04-03 17:04:35',
            ),
            5 => 
            array (
                'id' => 6,
                'page_name' => 'lookup',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:11:41',
                'updated_at' => '2018-04-03 17:11:41',
            ),
            6 => 
            array (
                'id' => 7,
                'page_name' => 'validation',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:11:58',
                'updated_at' => '2018-04-03 17:11:58',
            ),
            7 => 
            array (
                'id' => 8,
                'page_name' => 'zip code',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:12:14',
                'updated_at' => '2018-04-03 17:12:14',
            ),
            8 => 
            array (
                'id' => 9,
                'page_name' => 'text log',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:12:29',
                'updated_at' => '2018-04-03 17:12:29',
            ),
            9 => 
            array (
                'id' => 10,
                'page_name' => 'template',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:12:37',
                'updated_at' => '2018-04-03 17:12:37',
            ),
            10 => 
            array (
                'id' => 11,
                'page_name' => 'default template',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:12:50',
                'updated_at' => '2018-04-03 17:12:50',
            ),
            11 => 
            array (
                'id' => 12,
                'page_name' => 'user settings',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:14:38',
                'updated_at' => '2018-04-03 17:14:38',
            ),
            12 => 
            array (
                'id' => 13,
                'page_name' => 'user control',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:14:47',
                'updated_at' => '2018-04-03 17:14:47',
            ),
            13 => 
            array (
                'id' => 14,
                'page_name' => 'role management',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:14:58',
                'updated_at' => '2018-04-03 17:14:58',
            ),
            14 => 
            array (
                'id' => 15,
                'page_name' => 'site settings',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:15:09',
                'updated_at' => '2018-04-03 17:15:09',
            ),
            15 => 
            array (
                'id' => 16,
                'page_name' => 'database backup',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:15:21',
                'updated_at' => '2018-04-03 17:15:21',
            ),
            16 => 
            array (
                'id' => 17,
                'page_name' => 'queue',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-10 18:45:48',
                'updated_at' => '2018-04-10 18:45:48',
            ),
            17 => 
            array (
                'id' => 18,
                'page_name' => 'certificate',
                'action' => 'view|add|edit|delete|send|print',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 00:05:38',
                'updated_at' => '2018-04-25 11:35:34',
            ),
            18 => 
            array (
                'id' => 19,
                'page_name' => 'email_queue',
                'action' => 'add|edit|delete|view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-25 11:34:54',
                'updated_at' => '2018-04-25 11:34:54',
            ),
            19 => 
            array (
                'id' => 20,
                'page_name' => 'email log',
                'action' => 'Add|Edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 01:12:00',
                'updated_at' => '2018-05-22 01:12:00',
            ),
            20 => 
            array (
                'id' => 21,
                'page_name' => 'system menu',
                'action' => 'view|reports_view|tables_view|settings_view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 14:53:12',
                'updated_at' => '2018-05-22 14:53:12',
            ),
            21 => 
            array (
                'id' => 22,
                'page_name' => 'audit',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-01 23:25:38',
                'updated_at' => '2018-06-01 23:25:38',
            ),
            22 => 
            array (
                'id' => 23,
                'page_name' => 'maintenance',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-12 00:05:00',
                'updated_at' => '2019-03-12 00:05:00',
            ),
            23 => 
            array (
                'id' => 24,
                'page_name' => 'calendar1',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-12 00:09:59',
                'updated_at' => '2019-03-12 00:09:59',
            ),
            24 => 
            array (
                'id' => 25,
                'page_name' => 'state',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-11 18:07:05',
                'updated_at' => '2019-04-11 18:07:05',
            ),
            25 => 
            array (
                'id' => 26,
                'page_name' => 'region',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-11 18:07:34',
                'updated_at' => '2019-04-11 18:07:34',
            ),
            26 => 
            array (
                'id' => 27,
                'page_name' => 'county',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-11 18:07:57',
                'updated_at' => '2019-04-11 18:07:57',
            ),
            27 => 
            array (
                'id' => 28,
                'page_name' => 'district',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-11 18:08:12',
                'updated_at' => '2019-04-11 18:08:12',
            ),
            28 => 
            array (
                'id' => 29,
                'page_name' => 'city',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-11 18:08:37',
                'updated_at' => '2019-04-11 18:08:37',
            ),
            29 => 
            array (
                'id' => 30,
                'page_name' => 'timesheet',
                'action' => 'Add|Edit|View|Delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-23 16:58:52',
                'updated_at' => '2019-04-23 16:58:52',
            ),
            30 => 
            array (
                'id' => 31,
                'page_name' => 'vol timesheet',
                'action' => 'Add|View|Edit|Delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-23 17:00:20',
                'updated_at' => '2019-04-23 17:00:20',
            ),
            31 => 
            array (
                'id' => 32,
                'page_name' => 'support',
                'action' => 'add|edit|view|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:12:19',
                'updated_at' => '2019-04-24 22:12:19',
            ),
            32 => 
            array (
                'id' => 33,
                'page_name' => 'generals',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:29',
                'updated_at' => '2019-04-25 00:57:29',
            ),
            33 => 
            array (
                'id' => 34,
                'page_name' => 'items',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:37',
                'updated_at' => '2019-04-25 00:57:37',
            ),
            34 => 
            array (
                'id' => 35,
                'page_name' => 'location',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            35 => 
            array (
                'id' => 36,
                'page_name' => 'volunteer schedule',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            36 => 
            array (
                'id' => 37,
                'page_name' => 'high volume headers',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            37 => 
            array (
                'id' => 38,
                'page_name' => 'utilities',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            38 => 
            array (
                'id' => 39,
                'page_name' => 'layout_builder',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            39 => 
            array (
                'id' => 40,
                'page_name' => 'program-setup',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            40 => 
            array (
                'id' => 41,
                'page_name' => 'importer',
                'action' => 'view',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 00:57:53',
                'updated_at' => '2019-04-25 00:57:53',
            ),
            41 => 
            array (
                'id' => 42,
                'page_name' => 'Stipend Period',
                'action' => 'view|edit|add',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 2,
                'useru_id' => 2,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-24 16:56:00',
                'updated_at' => '2019-05-24 16:58:22',
            ),
            42 => 
            array (
                'id' => 43,
                'page_name' => 'Stipend Expense Item',
                'action' => 'view|add|edit|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-03 23:46:12',
                'updated_at' => '2019-06-04 00:08:10',
            ),
            43 => 
            array (
                'id' => 44,
                'page_name' => 'Stipend Time Item',
                'action' => 'view|add|edit|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:08:35',
                'updated_at' => '2019-06-04 00:08:35',
            ),
            44 => 
            array (
                'id' => 45,
                'page_name' => 'Sites',
                'action' => 'view|edit|add|delete|assign',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:45:58',
                'updated_at' => '2019-06-07 20:45:58',
            ),
            45 => 
            array (
                'id' => 46,
                'page_name' => 'Holiday',
                'action' => 'view|edit|add|delete',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:45:58',
                'updated_at' => '2019-06-07 20:45:58',
            ),
            46 => 
            array (
                'id' => 47,
                'page_name' => 'Sidebar',
                'action' => 'fiscal_menu|hvs_menu',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:45:58',
                'updated_at' => '2019-06-07 20:45:58',
            ),
            47 => 
            array (
                'id' => 48,
                'page_name' => 'tab',
                'action' => 'vsySummary',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 19,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-24 12:00:16',
                'updated_at' => '2019-07-24 12:00:16',
            ),
            48 => 
            array (
                'id' => 49,
                'page_name' => 'volunteer template manager',
                'action' => 'view|edit',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 06:59:38',
                'updated_at' => '2019-07-30 07:04:02',
            ),
        ));
        
        
    }
}