<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Dashboard all',
                'action' => 'view',
                'page_id' => 1,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:19:49',
                'updated_at' => '2018-04-03 17:19:49',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'reports All',
                'action' => 'add|edit|view|delete',
                'page_id' => 5,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:20:17',
                'updated_at' => '2019-04-24 20:10:52',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'validation all',
                'action' => 'add|edit|view|delete',
                'page_id' => 7,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:20:40',
                'updated_at' => '2019-04-24 20:11:26',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'zip code all',
                'action' => 'add|edit|view|delete',
                'page_id' => 8,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:20:51',
                'updated_at' => '2019-04-24 20:11:40',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'template all',
                'action' => 'add|edit|view|delete',
                'page_id' => 10,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:21:13',
                'updated_at' => '2019-04-24 20:09:33',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'default template all',
                'action' => 'add|edit|view|delete',
                'page_id' => 11,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:21:27',
                'updated_at' => '2019-04-24 22:09:35',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'user settings all',
                'action' => 'add|edit|view|delete',
                'page_id' => 12,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:21:40',
                'updated_at' => '2019-04-24 20:08:50',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'user control all',
                'action' => 'add|edit|view|delete',
                'page_id' => 13,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:21:51',
                'updated_at' => '2019-04-24 20:08:33',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'role management all',
                'action' => 'add|edit|view|delete',
                'page_id' => 14,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:22:02',
                'updated_at' => '2019-04-24 20:07:12',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'site settings all',
                'action' => 'add|edit|view|delete',
                'page_id' => 15,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:22:15',
                'updated_at' => '2019-04-24 20:09:06',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'default template all',
                'action' => 'add|edit|view|delete',
                'page_id' => 16,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:22:28',
                'updated_at' => '2018-04-03 17:22:28',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'user setting all',
                'action' => 'add|edit|view|delete',
                'page_id' => 17,
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => '2019-04-24 20:10:28',
                'created_at' => '2018-04-03 17:22:41',
                'updated_at' => '2019-04-24 20:10:28',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'user controll all',
                'action' => 'add|edit|view|delete',
                'page_id' => 18,
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => '2019-04-24 20:09:46',
                'created_at' => '2018-04-03 17:22:54',
                'updated_at' => '2019-04-24 20:09:46',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'role management all',
                'action' => '',
                'page_id' => 19,
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => '2019-04-24 20:10:24',
                'created_at' => '2018-04-03 17:23:06',
                'updated_at' => '2019-04-24 20:10:24',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'email log all',
                'action' => 'view|delete',
                'page_id' => 20,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:23:21',
                'updated_at' => '2019-04-24 20:10:11',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'dbBackup all',
                'action' => 'add|edit|view|delete',
                'page_id' => 21,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-03 17:23:34',
                'updated_at' => '2018-04-03 17:23:34',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Maintenance All',
                'action' => 'add|edit|view|delete',
                'page_id' => 23,
                'co_no' => 1,
                'is_deleted' => 1,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => '2019-03-14 17:43:39',
                'created_at' => '2018-04-09 16:23:48',
                'updated_at' => '2019-03-14 17:43:39',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'state All',
                'action' => 'view',
                'page_id' => 25,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-10 18:46:01',
                'updated_at' => '2019-04-24 20:11:00',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'region all',
                'action' => 'add|edit|view|delete',
                'page_id' => 26,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-12 00:06:07',
                'updated_at' => '2019-04-24 20:10:38',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'county All',
                'action' => 'add|edit|view|delete',
                'page_id' => 27,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-25 11:36:31',
                'updated_at' => '2019-04-24 20:09:55',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'timesheets full control',
                'action' => 'view|add|edit|delete',
                'page_id' => 30,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 01:12:18',
                'updated_at' => '2019-04-24 20:11:14',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'system menu access',
                'action' => 'view',
                'page_id' => 31,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 14:53:30',
                'updated_at' => '2018-05-22 14:53:30',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Audit all Admin',
                'action' => 'add|edit|view|delete',
                'page_id' => 34,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-01 23:25:54',
                'updated_at' => '2018-06-01 23:25:54',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Maintenance All',
                'action' => 'add|edit|view|delete',
                'page_id' => 35,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-12 00:06:01',
                'updated_at' => '2019-03-12 00:06:01',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'calendar1 all',
                'action' => 'add|edit|view|delete',
                'page_id' => 36,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-12 00:12:58',
                'updated_at' => '2019-03-12 00:12:58',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'vol timesheet add',
                'action' => 'Add',
                'page_id' => 31,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-23 17:00:40',
                'updated_at' => '2019-04-23 17:00:40',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'vol timesheet all',
                'action' => 'Add|View|Edit|Delete',
                'page_id' => 31,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-23 17:00:55',
                'updated_at' => '2019-04-23 17:00:55',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'support all',
                'action' => 'add|edit|view|delete',
                'page_id' => 32,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:12:36',
                'updated_at' => '2019-04-24 22:12:36',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'note all',
                'action' => 'view|add|edit|delete',
                'page_id' => 4,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:13:25',
                'updated_at' => '2019-04-24 22:13:25',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'text log all',
                'action' => 'add|edit|view|delete',
                'page_id' => 9,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:14:41',
                'updated_at' => '2019-04-24 22:14:41',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'location',
                'action' => 'add|edit|view|delete',
                'page_id' => 33,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:14:41',
                'updated_at' => '2019-04-24 22:14:41',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'city all',
                'action' => 'add|edit|view|delete',
                'page_id' => 29,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:14:41',
                'updated_at' => '2019-04-24 22:14:41',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'district',
                'action' => 'add|edit|view|delete',
                'page_id' => 28,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-24 22:14:41',
                'updated_at' => '2019-04-24 22:14:41',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Lookup all',
                'action' => 'add|edit|view|delete',
                'page_id' => 6,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'volunteer schedule all',
                'action' => 'add|edit|view|delete',
                'page_id' => 36,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'high volume headers all',
                'action' => 'add|edit|view|delete',
                'page_id' => 37,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'maintenance all',
                'action' => 'add|edit|view|delete',
                'page_id' => 23,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'audit all',
                'action' => 'add|edit|view|delete',
                'page_id' => 22,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'utilities all',
                'action' => 'add|edit|view|delete',
                'page_id' => 38,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'layout_builder all',
                'action' => 'add|edit|view|delete',
                'page_id' => 39,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'program-setup all',
                'action' => 'add|edit|view|delete',
                'page_id' => 40,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'importer all',
                'action' => 'add|edit|view|delete',
                'page_id' => 41,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Period View',
                'action' => 'view|edit|add',
                'page_id' => 42,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 2,
                'useru_id' => 2,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-24 16:57:05',
                'updated_at' => '2019-05-24 18:24:34',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Stipend Expense Item View',
                'action' => 'view',
                'page_id' => 43,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-03 23:48:36',
                'updated_at' => '2019-06-04 00:56:52',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Stipend Time Item View',
                'action' => 'view',
                'page_id' => 44,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:11:25',
                'updated_at' => '2019-06-04 00:55:03',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Stipend Time Item Edit',
                'action' => 'edit',
                'page_id' => 44,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:55:42',
                'updated_at' => '2019-06-04 00:55:42',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Stipend Time Item Add',
                'action' => 'add',
                'page_id' => 44,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:55:59',
                'updated_at' => '2019-06-04 00:56:18',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Stipend Expense Item Edit',
                'action' => 'edit',
                'page_id' => 43,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:57:10',
                'updated_at' => '2019-06-04 00:57:10',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Stipend Expense Item Add',
                'action' => 'add',
                'page_id' => 43,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-04 00:57:27',
                'updated_at' => '2019-06-04 00:57:27',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Site all',
                'action' => 'view|edit|add|delete|assign',
                'page_id' => 45,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:46:32',
                'updated_at' => '2019-06-07 20:46:32',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'System menu all',
                'action' => 'reports_view|tables_view|settings_view',
                'page_id' => 21,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:46:32',
                'updated_at' => '2019-06-07 20:46:32',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'System menu reports only',
                'action' => 'reports_view',
                'page_id' => 21,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:46:32',
                'updated_at' => '2019-06-07 20:46:32',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Holiday All',
                'action' => 'view|add|edit|delete',
                'page_id' => 46,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-06-07 20:46:32',
                'updated_at' => '2019-06-07 20:46:32',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Sidebar Fiscal Menu',
                'action' => 'fiscal_menu',
                'page_id' => 47,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 01:12:18',
                'updated_at' => '2019-04-24 20:11:14',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Sidebar Hvs Menu',
                'action' => 'hvs_menu',
                'page_id' => 47,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-22 01:12:18',
                'updated_at' => '2019-04-24 20:11:14',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'vsySummary dashboard',
                'action' => 'vsySummary',
                'page_id' => 48,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 19,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-24 12:00:42',
                'updated_at' => '2019-07-24 12:00:42',
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'volunter template manager all',
                'action' => 'view|edit',
                'page_id' => 49,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-07-30 07:01:11',
                'updated_at' => '2019-07-30 07:04:23',
            ),
        ));
        
        
    }
}