<?php

use Illuminate\Database\Seeder;

class SiteSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('site_settings')->delete();

        \DB::table('site_settings')->insert(array(
            0 =>
            array(
                'id' => 1,
                'code' => 'dashboard_logo',
                'value' => 'logo.png',
                'description' => 'Dashboard Logo',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-10 08:31:50',
                'updated_at' => '2018-04-10 08:33:09',
            ),
            1 =>
            array(
                'id' => 2,
                'code' => 'dashboard_logo1',
                'value' => 'logo1.png',
                'description' => 'Dashboard Logo 2',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-10 08:33:32',
                'updated_at' => '2018-04-10 08:33:32',
            ),
            2 =>
            array(
                'id' => 3,
                'code' => 'email_mode',
                'value' => 'queue',
                'description' => 'mode of sending email
value can be auto , queue',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-18 02:51:18',
                'updated_at' => '2018-07-15 11:21:13',
            ),
            3 =>
            array(
                'id' => 4,
                'code' => 'date_format',
                'value' => 'MM/DD/YYYY',
                'description' => 'date format for all  files',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => 5,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-26 07:07:37',
                'updated_at' => '2018-04-27 10:45:52',
            ),
            4 =>
            array(
                'id' => 5,
                'code' => 'date_format_php',
                'value' => 'm/d/Y',
                'description' => 'date format for php',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 5,
                'useru_id' => 5,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-27 10:44:10',
                'updated_at' => '2018-04-27 10:46:04',
            ),
            5 =>
            array(
                'id' => 6,
                'code' => 'email_from_name',
                'value' => 'Foster Grandparent Programs',
                'description' => 'This is dynamic name',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-31 08:01:29',
                'updated_at' => '2018-05-31 08:04:13',
            ),
            6 =>
            array(
                'id' => 7,
                'code' => 'EmailQueue-Volunters',
                'value' => 'false',
                'description' => 'Sets flag whether or not to send email credentials while creation',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-06 13:10:38',
                'updated_at' => '2018-06-06 13:11:01',
            ),
            7 =>
            array(
                'id' => 8,
                'code' => 'site_email',
                'value' => 'support@zeuslogic.com',
                'description' => 'site email address',
                'section' => NULL,
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-14 11:08:46',
                'updated_at' => '2018-06-14 11:08:46',
            ),
            8 =>
            array(
                'id' => 9,
                'code' => 'new_volunteer_registered',
                'value' => 'True',
                'description' => 'True or False for new registered volunteer notifications',
                'section' => 'Notification',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-26 07:30:28',
                'updated_at' => '2018-06-26 07:30:28',
            ),
            9 =>
            array(
                'id' => 10,
                'code' => 'is_delete',
                'value' => 'False',
                'description' => 'True or False value to enable delete unwanted items',
                'section' => 'Application',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-29 13:14:28',
                'updated_at' => '2018-07-25 14:57:50',
            ),
            10 =>
            array(
                'id' => 11,
                'code' => 'salutation',
                'value' => 'True',
                'description' => 'Salutation True or False value to show or hide the field',
                'section' => 'Client',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-07-17 08:44:01',
                'updated_at' => '2018-07-24 09:06:12',
            ),
            11 =>
            array(
                'id' => 12,
                'code' => 'fiscal_year',
                'value' => '2019',
                'description' => 'pay_periods table\'s fiscal_year field value',
                'section' => 'Payperiod',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-18 09:59:09',
                'updated_at' => '2019-03-18 09:59:09',
            ),
            12 =>
            array(
                'id' => 13,
                'code' => 'stipend_rate',
                'value' => '2',
                'description' => 'stipend rate for any particular time hrs , rate per hr',
                'section' => 'PayPeriod',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 3,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-17 09:34:34',
                'updated_at' => '2019-04-17 09:34:34',
            ),
            13 =>
            array(
                'id' => 14,
                'code' => 'follow_approval',
                'value' => 'True',
                'description' => 'Value can be True or False for giving approval permission directly higher roles or not',
                'section' => 'PayPeriod',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-04-25 12:17:56',
                'updated_at' => '2019-04-25 12:17:56',
            ),
            14 =>
            array(
                'id' => 15,
                'code' => 'category_code',
                'value' => '90000000',
                'description' => 'can be changed according to the requirements',
                'section' => 'SpreadhSheet',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-10 08:13:57',
                'updated_at' => '2019-05-10 08:13:57',
            ),
            15 =>
            array(
                'id' => 16,
                'code' => 'timesheets_override',
                'value' => 'all',
                'description' => 'can be changed according to the requirements',
                'section' => 'Timesheets',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-10 08:13:57',
                'updated_at' => '2019-05-10 08:13:57',
            ),
            16 =>
            array(
                'id' => 17,
                'code' => 'eto_calculation_unit',
                'value' => '0.1724',
                'description' => 'ETO Calculation Unit',
                'section' => 'Timesheets',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-10 08:13:57',
                'updated_at' => '2019-05-10 08:13:57',
            ),
        ));
    }
}
