<?php

use Illuminate\Database\Seeder;

class ValidationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('validations')->delete();
        
        \DB::table('validations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'validation_form',
                'value' => 'code:required,value:required',
                'description' => 'Required Fieldss',
                'section' => 'Validation',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 4,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-03-19 14:07:08',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'zip_code_form',
                'value' => 'zip_code:required,city:required,county:required,state:required',
                'description' => 'Required Fields',
                'section' => 'Zip Code',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:25:21',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'lookup_form',
                'value' => 'code:required,value:required|string',
                'description' => 'Required Fields',
                'section' => 'Lookup',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:21:52',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'organization_form',
                'value' => 'lic_no:required,cname:required|string,add1:required|string,city:required|string,zip:required|numeric,state:required|string,phone:required,company_email:required|email,type:required,org_fname:required,org_lname:required,fname:required,lname:required,personal_email:required,cell_phone:required,vet_lic:required',
                'description' => 'Required Fields',
                'section' => 'Providers',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:22:07',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'page_form',
                'value' => 'page_name:required,action:required',
                'description' => 'Required Fields',
                'section' => 'Role',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:22:30',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'role_form',
                'value' => 'name:required,label:required',
                'description' => 'required',
                'section' => 'Role',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:23:31',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'permission_form',
                'value' => 'name:required,page_id:required',
                'description' => 'Required Field',
                'section' => 'Role',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2018-06-22 11:22:44',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'email_template_form',
                'value' => 'section:required,temp_code:required,temp_name:required,temp_type:required,temp_html:required',
                'description' => 'Required Fields',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-03-27 11:21:31',
                'updated_at' => '2018-06-22 11:28:25',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'note_form',
                'value' => 'title:required,notes:required',
                'description' => 'Required Fields',
                'section' => 'Note',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-09 08:29:38',
                'updated_at' => '2018-06-22 11:22:00',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'site_setting_form',
                'value' => 'code:required,value:required',
                'description' => 'Required Fields',
                'section' => 'Site Settings',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-04-10 08:31:47',
                'updated_at' => '2018-06-22 11:23:39',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'email_send',
                'value' => 'to:required|email,subject:required,message:required',
                'description' => 'Required Files',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-29 10:27:19',
                'updated_at' => '2018-06-22 11:19:08',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'email_settings_form',
                'value' => 'email:required|email,email_from:required,serverName:required,password:required,mail_type:required',
                'description' => 'Required fields',
                'section' => 'Email Template',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-30 10:33:36',
                'updated_at' => '2018-06-22 11:19:18',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'support_form',
                'value' => 'title:required',
                'description' => 'validation for  support form',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 07:04:08',
                'updated_at' => '2018-07-16 08:42:40',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'support_comment_form',
                'value' => 'comment:required',
                'description' => 'Required For Comment_support_form',
                'section' => 'Support',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-06-08 08:23:23',
                'updated_at' => '2018-06-22 11:23:45',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'pay_period_form',
                'value' => 'start_date:required,end_date:required,fiscal_year:required,period_starts_from:required,interval:required',
                'description' => 'pay_periods table validation',
                'section' => 'PayPeriod',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-18 08:04:39',
                'updated_at' => '2019-03-21 12:34:05',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'timeSheetAddForm',
                'value' => 'period_id:required',
                'description' => 'Validations for adding new timesheet',
                'section' => 'TimeSheet',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 4,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-21 08:05:30',
                'updated_at' => '2019-03-21 08:05:30',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'volunteer_register',
                'value' => 'first_name:required,last_name:required,add1:required,city:required',
                'description' => 'Required Fields of add volunteer form',
                'section' => 'Volunteer',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-21 09:26:59',
                'updated_at' => '2019-04-05 07:59:40',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'holiday_create',
                'value' => 'name:required,hol_date:required,cal_type:required',
                'description' => 'Required Fields of holiday',
                'section' => 'Holiday',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-21 12:22:06',
                'updated_at' => '2019-03-21 12:22:06',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'site_create',
                'value' => 'site_name:required,add1:required',
                'description' => 'Required Fields of Site',
                'section' => 'Site',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-21 13:01:04',
                'updated_at' => '2019-04-05 08:34:11',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'stipend_item_create',
                'value' => 'item_name:required,unit_amount:required,category:required,fund_code:required,year:required',
                'description' => 'Stipend Item Create table validation',
                'section' => 'StipendItem',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-26 07:50:54',
                'updated_at' => '2019-06-03 13:34:28',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'state_create',
                'value' => 'state_name:required,state_code:required',
                'description' => 'states table validation',
                'section' => 'State',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 07:28:33',
                'updated_at' => '2019-03-27 07:28:33',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'region_create',
                'value' => 'state_id:required,region_name:required,region_code:required',
                'description' => 'regions table validations',
                'section' => 'LocationRegion',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 07:32:33',
                'updated_at' => '2019-03-28 13:47:30',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'district_create',
                'value' => 'county_id:required,district_name:required,district_code:required',
                'description' => 'districts table validation',
                'section' => 'LocationDistrict',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 07:33:51',
                'updated_at' => '2019-03-28 13:10:43',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'city_create',
                'value' => 'district_id:required,city_name:required,city_code:required,zip_code:required',
                'description' => 'cities table validations',
                'section' => 'LocationCity',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 07:34:54',
                'updated_at' => '2019-03-28 13:51:49',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'county_create',
                'value' => 'region_id:required,county_name:required,county_code:required',
                'description' => 'counties table validation',
                'section' => 'LocationCounty',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 7,
                'useru_id' => 7,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-27 07:36:22',
                'updated_at' => '2019-03-28 13:47:45',
            ),
        ));
        
        
    }
}