<?php

use Illuminate\Database\Seeder;

class ZipCodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zip_codes')->delete();
        
        \DB::table('zip_codes')->insert(array (
            0 => 
            array (
                'id' => 100,
                'zip_code' => 18060,
                'city' => 'North Vadashire',
                'county' => 'South',
                'state' => 'california',
                'district' => 'ut',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            1 => 
            array (
                'id' => 101,
                'zip_code' => 9289,
                'city' => 'Mantefort',
                'county' => 'North',
                'state' => 'california',
                'district' => 'vero',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            2 => 
            array (
                'id' => 102,
                'zip_code' => 24741,
                'city' => 'Lylaton',
                'county' => 'North',
                'state' => 'california',
                'district' => 'ea',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            3 => 
            array (
                'id' => 103,
                'zip_code' => 17592,
                'city' => 'East Joshview',
                'county' => 'Port',
                'state' => 'california',
                'district' => 'sit',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            4 => 
            array (
                'id' => 104,
                'zip_code' => 61289,
                'city' => 'South Nikki',
                'county' => 'North',
                'state' => 'california',
                'district' => 'iste',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            5 => 
            array (
                'id' => 105,
                'zip_code' => 15147,
                'city' => 'South Eldred',
                'county' => 'Lake',
                'state' => 'california',
                'district' => 'et',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            6 => 
            array (
                'id' => 106,
                'zip_code' => 48254,
                'city' => 'Greenfelderfurt',
                'county' => 'East',
                'state' => 'california',
                'district' => 'et',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            7 => 
            array (
                'id' => 107,
                'zip_code' => 17315,
                'city' => 'Port Ceceliafurt',
                'county' => 'North',
                'state' => 'california',
                'district' => 'ut',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            8 => 
            array (
                'id' => 108,
                'zip_code' => 72511,
                'city' => 'Port Geraldfort',
                'county' => 'South',
                'state' => 'california',
                'district' => 'est',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            9 => 
            array (
                'id' => 109,
                'zip_code' => 88833,
                'city' => 'New Josephineview',
                'county' => 'New',
                'state' => 'california',
                'district' => 'aliquam',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:17',
                'updated_at' => '2019-03-25 14:31:17',
            ),
            10 => 
            array (
                'id' => 110,
                'zip_code' => 77592,
                'city' => 'Reichertfort',
                'county' => 'Port',
                'state' => 'california',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            11 => 
            array (
                'id' => 111,
                'zip_code' => 99588,
                'city' => 'New Shanel',
                'county' => 'South',
                'state' => 'georgia',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            12 => 
            array (
                'id' => 112,
                'zip_code' => 526,
                'city' => 'South Anastacio',
                'county' => 'New',
                'state' => 'michigan',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            13 => 
            array (
                'id' => 113,
                'zip_code' => 30372,
                'city' => 'Dejahland',
                'county' => 'East',
                'state' => 'north dakota',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            14 => 
            array (
                'id' => 114,
                'zip_code' => 65816,
                'city' => 'North Colinborough',
                'county' => 'East',
                'state' => 'ohio',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            15 => 
            array (
                'id' => 115,
                'zip_code' => 18093,
                'city' => 'New Rosemouth',
                'county' => 'Port',
                'state' => 'north carolina',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            16 => 
            array (
                'id' => 116,
                'zip_code' => 12803,
                'city' => 'Erickatown',
                'county' => 'New',
                'state' => 'mississippi',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            17 => 
            array (
                'id' => 117,
                'zip_code' => 58212,
                'city' => 'Port Victoriaport',
                'county' => 'New',
                'state' => 'arkansas',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            18 => 
            array (
                'id' => 118,
                'zip_code' => 63853,
                'city' => 'West Hobart',
                'county' => 'North',
                'state' => 'iowa',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            19 => 
            array (
                'id' => 119,
                'zip_code' => 39759,
                'city' => 'East Itzel',
                'county' => 'West',
                'state' => 'kentucky',
                'district' => 'naccasa',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:33',
                'updated_at' => '2019-03-25 14:31:33',
            ),
            20 => 
            array (
                'id' => 120,
                'zip_code' => 59067,
                'city' => 'Sporerstad',
                'county' => 'New',
                'state' => 'arizona',
                'district' => 'natus',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            21 => 
            array (
                'id' => 121,
                'zip_code' => 50954,
                'city' => 'West Zena',
                'county' => 'Lake',
                'state' => 'michigan',
                'district' => 'doloribus',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            22 => 
            array (
                'id' => 122,
                'zip_code' => 12349,
                'city' => 'Chynaland',
                'county' => 'Port',
                'state' => 'illinois',
                'district' => 'necessitatibus',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            23 => 
            array (
                'id' => 123,
                'zip_code' => 83012,
                'city' => 'Stantontown',
                'county' => 'West',
                'state' => 'district of columbia',
                'district' => 'placeat',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            24 => 
            array (
                'id' => 124,
                'zip_code' => 22518,
                'city' => 'Nikkiside',
                'county' => 'Lake',
                'state' => 'new york',
                'district' => 'hic',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            25 => 
            array (
                'id' => 125,
                'zip_code' => 8396,
                'city' => 'West Yeseniastad',
                'county' => 'Lake',
                'state' => 'alaska',
                'district' => 'nisi',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            26 => 
            array (
                'id' => 126,
                'zip_code' => 99552,
                'city' => 'Allisonberg',
                'county' => 'Lake',
                'state' => 'new york',
                'district' => 'reiciendis',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            27 => 
            array (
                'id' => 127,
                'zip_code' => 10526,
                'city' => 'East Betty',
                'county' => 'East',
                'state' => 'wyoming',
                'district' => 'maiores',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            28 => 
            array (
                'id' => 128,
                'zip_code' => 89413,
                'city' => 'Buckchester',
                'county' => 'Lake',
                'state' => 'tennessee',
                'district' => 'qui',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
            29 => 
            array (
                'id' => 129,
                'zip_code' => 98877,
                'city' => 'Morristown',
                'county' => 'Port',
                'state' => 'iowa',
                'district' => 'repellendus',
                'co_no' => 1,
                'is_deleted' => 0,
                'is_active' => 1,
                'userc_id' => 0,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-03-25 14:31:41',
                'updated_at' => '2019-03-25 14:31:41',
            ),
        ));
        
        
    }
}