@include('default.layouts.doctype')
@include('default.layouts.header')
@include('default.layouts.sidebar')
@yield('content')
@include('default.layouts.footerbar')
@include('default.layouts.quickSidebar')
@include('default.layouts.components.modal')
@include('default.layouts.footer')
