<html>
<head>
    <title>Title</title>
    <style>
        .body {
            font-size: 11px;
            font-family: 'Poppins', sans-serif;
        }

        .searchArea {
            width: 100%;
            float: left;
            font-size: 11px;
            font-family: 'Poppins', sans-serif;
        }

        .searchArea .part {
            width: 50%;
            float: left;
            text-align: right;
        }

        table.headerArea {
            width: 100%;
            margin-bottom: 20px;
        }

        table.headerArea tr td {
            width: 40%;
            font-family: 'Poppins', sans-serif;
        }

        table.options {
            width: 80%;
            float: left;
            margin-bottom: 20px;
        }

        table.options tr td {
            padding: 5px;
            font-size: 11px;
            font-family: 'Poppins', sans-serif;
        }

        /*table.options tr td:first-child {*/
            /*text-align: right;*/
        /*}*/

        table.dataTable {
            margin-top: 20px;
            width: 100%;
        }

        table.dataTable tr th {
            text-align: left;
        }

        table.dataTable tr th, table.dataTable tr td {
            padding: 5px;
            font-size: 11px;
            font-family: 'Poppins', sans-serif;
        }

        table.dataTable tbody tr:last-child {
            font-weight: bolder;
        }
    </style>
</head>
<body>
<?php
if (isset($datas))
    $data = $datas;
if (isset($fields))
    $field = $fields;
$request = array_key_exists('request', $data) ? $data['request'] : [];
$table = array_key_exists('table', $data) ? $data['table'] : '';
unset($data['request']);
unset($data['table']);
$dateArr = ['jul', 'aug', 'sept', 'oct', 'nov', 'dec', 'jan', 'feb', 'mar', 'apr', 'may', 'jun']
?>
<table class="headerArea">
    <tr style="width: 100%;">
        <td style="width: 20%">
            <img src='{{ base64_logo() }}'
                 alt="Email" style="background-color:white;display: block; height: 50px;filter: Alpha(opacity=100); opacity: 1;"/>
        </td>
        <td style="width:20%; font-family: 'Poppins', sans-serif;font-size: 12px; text-align: center;">
            <strong>Foster Grandparents Program</strong><br>
            <strong style="margin-top: 10px">{{ strtoupper($table) }}</strong>
        </td>
        <td style="width: 20%; font-family: 'Poppins', sans-serif;font-size: 11px; text-align: right;">
            <?php echo 'Date: ' . date('m/d/Y H:i:s');?><br>
            {{--Report Generated By: {{auth()->user()->client->fname}} {{auth()->user()->client->mname}} {{auth()->user()->client->lname}}--}}
        </td>
    </tr>
</table>

<table class="options">
    {{--<tr>--}}
        {{--<td></td>--}}
        {{--<td><strong>Search Criteria </strong></td>--}}
    {{--</tr>--}}
    @foreach($request as $d=>$v)
        <tr>
            <td style="width:20%;">{{$d}}:</td>
            <td>@if($v==null) All @elseif(is_array($v) && count($v)>0) {{implode(', ',$v)}} @else {{$v}} @endif</td>
        </tr>
    @endforeach
</table>

<table class="dataTable" border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;" align="center">
    <thead>
    <tr>
        @foreach($field as $key => $value)
            @if(preg_match('/>$/', $value))
                <?php $value = preg_replace('/>$/', '', $value) ?>
                <th style="text-align:right;">{{ $value }}</th>
            @elseif(preg_match('/=$/', $value))
                <?php $value = preg_replace('/=$/', '', $value) ?>
                <th style="text-align:center;">{{ $value }}</th>
            @else
                <th style="text-align:left;">{{ str_replace('Raw', '', $value) }}</th>
            @endif
        @endforeach
    </tr>
    </thead>
    <tbody>
    @foreach($data as $da)
        <tr>
            @foreach($da as $k => $value)
                @if(preg_match('/>$/', $value))
                    <?php $value = preg_replace('/>$/', '', $value) ?>
                    <td style="text-align:right;">{{ $value }}</td>
                @elseif(preg_match('/=$/', $value))
                    <?php $value = preg_replace('/=$/', '', $value) ?>
                    <td style="text-align:center;">{{ $value }}</td>
                @else
                    <td style="text-align:left;">{{ $value }}</td>
                @endif
            @endforeach
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>